name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure v
      run: make cmake-debug

    - name: Build
      run: make build-debug

    - name: Tests
      run: make tests

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure cmake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build_debug -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build_debug --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build_debug
      run: ctest -V -C ${{env.BUILD_TYPE}}
